var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res) {
  res.send('Hello World!');
});
// router.get('/math', function(req, res, next) {
//   res.send('Hello World!');
// });


module.exports = router;


// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
// ADD MATH ROUTE AND CONNECT THE NOW WORKING EXPRESS ROUTES
